services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${EASYSTUDY_SERVER_PORT}:${EASYSTUDY_SERVER_PORT}
    environment:
      EASYSTUDY_ENV: ${EASYSTUDY_ENV}
      EASYSTUDY_SERVER_HOST: ${EASYSTUDY_SERVER_HOST}
      EASYSTUDY_SERVER_PORT: ${EASYSTUDY_SERVER_PORT}
      EASYSTUDY_POSTGRES_HOST: ${EASYSTUDY_POSTGRES_HOST}
      EASYSTUDY_POSTGRES_PORT: ${EASYSTUDY_POSTGRES_PORT}
      EASYSTUDY_POSTGRES_DATABASE: ${EASYSTUDY_POSTGRES_DATABASE}
      EASYSTUDY_POSTGRES_USERNAME: ${EASYSTUDY_POSTGRES_USERNAME}
      EASYSTUDY_POSTGRES_PASSWORD: ${EASYSTUDY_POSTGRES_PASSWORD}
      EASYSTUDY_REDIS_HOST: ${EASYSTUDY_REDIS_HOST}
      EASYSTUDY_REDIS_PORT: ${EASYSTUDY_REDIS_PORT}
      EASYSTUDY_REDIS_PASSWORD: ${EASYSTUDY_REDIS_PASSWORD}
      EASYSTUDY_REDIS_DB: ${EASYSTUDY_REDIS_DB}
    depends_on:
      psql:
        condition: service_healthy
    networks:
      - easystudy
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${EASYSTUDY_POSTGRES_DATABASE}
      POSTGRES_USER: ${EASYSTUDY_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${EASYSTUDY_POSTGRES_PASSWORD}
    ports:
      - "${EASYSTUDY_POSTGRES_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${EASYSTUDY_POSTGRES_USERNAME} -d ${EASYSTUDY_POSTGRES_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - easystudy

volumes:
  psql_volume:
networks:
  easystudy:
